### ISSUE TITLE
Feature idea - Keeping main-module-browser field triplet together in package.json on defaults

### ISSUE THREAD

**Issue by revelt** [camacho/format-package#1]
Hi! First, thanks for this amazing tool. I'm about to call the first dibs in your "dependents" [list](https://www.npmjs.com/browse/depended/format-package) on npm :)

---

When running on **default setting**, I noticed that the `main` key is kept sensibly towards the top, but `browser` and `module` keys are sorted alphabetically among "unrecognised" keys.

In the nearest future, more and more libs will start using `module` and `browser` keys and it would be nice if the default setting on `format-package` would gang them together.

For example, Rollup [boilerplate](https://github.com/rollup/rollup-starter-lib/blob/babel/package.json) is outputing them and in my libraries I set something like:

```js
...
"main": "dist/util-nonempty.cjs.js",
"browser": "dist/util-nonempty.umd.js",
"module": "dist/util-nonempty.esm.js",
"scripts": {
  "build": "rollup -c && npm run format:pkg",
...
```

It would be nice to visually-`grep` are the paths correct, are the names the same, are extensions right – all in one place.

@camacho What do you think about this idea? Would it be sensible to put `browser` and `module` keys right under `main`, on the default `format-package` setting?

Cheers!

**Comment by camacho** [comment]
This sounds like a good idea to me. It's tricky to know how much opinion we should bake in versus let users set with their own config, but I don't see anything controversial about adding those keys under `main`

**Comment by revelt** [comment]
Awesome! 

Implementation-wise, do you have to add two new fields, `module` and `browser` under `main` in https://github.com/camacho/format-package/blob/master/lib/defaults/order.json and that's it?

**Comment by camacho** [comment]
@revelt yup!

**Comment by camacho** [comment]
This should now be updated in the `3.0` release today

**Comment by revelt** [comment]
awesome!

**Comment by revelt** [comment]
By the way, even if I tried to switch to `clinton` which also does sorting on `--fix` mode, I can't use it because it would "fix" many other things that don't need fixing. I like `format-package` because it does one thing only. This is a very important USP of this lib.
