### ISSUE TITLE
getting "format is not a function" error

### ISSUE THREAD

**Issue by revelt** [camacho/format-package#109]
hi all,

Consider this:

```js
const format = require("format-package");
const dummyPackage = {
    "dependencies": {},
    "name": "test"
};

(async () => {
    const formattedPackage = await format(dummyPackage);
    console.log(formattedPackage);
})();
```

I created a Runkit playground for it:
https://runkit.com/royst0n/format-package-test

It complains `format` is not a function! I had same thing wired up on my script ages ago and just recently I noticed rejected promise warnings and started digging.

So far it seems it's not options object or node version issue (Runkit allows to toggle different Node versions, tried all) and it seems a _default_ function is indeed exported as far as I can see in `node_modules`...

Please investigate when you have a second. Thank you.

**Comment by camacho** [comment]
Since moving to TS, it looks like the import syntax has changed: 

```ts
const { default: format } = require('format-package')
// or in TS
import format from 'format-package'
```

https://runkit.com/camacho/format-package-test

**Comment by revelt** [comment]
aha! Thank you
