### ISSUE TITLE
Flag for non-0 exit code if formatting changed the file

### ISSUE THREAD

**Issue by GerkinDev** [camacho/format-package#112]
Hey there !

Would it be possible to add a couple of flags so that `format-package` could be executed as a pre-commit **test**? I saw it is possible to use lint-staged, but I have a pre-commit hook that checks if everything is OK and I'd like to check package.json too

This would be like this:

```sh
format-package [--check-formated,-c]
```

If the serialization of the formatted package.json is different to the actual file, this would return a non-0 exit code.

Thanks !

**Comment by camacho** [comment]
Hi @GerkinDev this seems like a good addition. Is this something you want to tackle?

**Comment by GerkinDev** [comment]
I'm not familiar with yargs, but I gonna give it a shot when I have some time. I'm currently focused on other things right now. If you have a couple weeks or a month, I will. Otherwise, if you do it yourself, please keep me updated

Cheers! :beers:

**Comment by GerkinDev** [comment]
Hi, I'm back on this since I'm reworking our CI process.

About this thing, how do you think this should behave?
On one hand, I would see this like most linters, eg not changing without a `--fix` flag.
On the other hand, this would be  a breaking change, probably not desirable.

So, maybe the best compromise would be like a `--check-only` flag, that would *not* format the file, but only checks for correctness, and return `1` exit code if invalid.

**Comment by camacho** [comment]
I would use a `--check/-c` flag.

If files changed from formatting (even if `--write` is passed) the process exits with a `1`. 

Additionally, if **only** `--check/-c` is passed, there is no format output printed in the console.

**Comment by GerkinDev** [comment]
\o/ thank you so much for the merge! Have a wonderful day!

**Comment by GerkinDev** [comment]
Do you have any idea about when you'll be able to release this on npm so that I can update my workflows?

**Comment by camacho** [comment]
@GerkinDev see #126
