### ISSUE TITLE
Avoid sorting "exports" keys. The order is significant.

### ISSUE THREAD

**Issue by jaketrent** [camacho/format-package#116]
Conditional exports have been supported in package.json starting behind a flag in node@13 and now in general release in node@15.

The key in package.json is called `"exports"`.  The key order is significant.  From the docs:

> Within the "exports" object, key order is significant. During condition matching, earlier entries have higher priority and take precedence over later entries.

https://nodejs.org/api/packages.html#packages_conditional_exports

It would be great to have the default behavior be to leave this field alone.

Appendix:

One can theoretically get around this by using the transformations. I attempted this in my environment, but whatever the reason couldn't make it work. So I've removed the format-package for now as a part of our process but would like to get it back when I have the time to re-investigate my config or upgrade when this feature is added.

Perhaps this would work for someone else in format-package.config.js.  Probably, because I think our main problem was that the config wasn't being used.

```
module.exports = {
  transformations: {
    exports(key, value) { return [key, value] }
  }
}
```

**Comment by GerkinDev** [comment]
I had repeated issues because of this. Note that nested fields of `typesVersions` for typescript mappings are order-dependent too.

**Comment by GerkinDev** [comment]
@camacho I could PR for this (and fix #117 btw) if you can guarantee me you'll merge those quickly. I had pretty bad experiences with submitting PRs that are never merged and result in huge tons of conflicts I have to fix multiple times.

**Comment by camacho** [comment]
This will probably be delayed by a couple weeks. I have a draft PR I'll put up shortly that addresses the ordering and "check" issues. Thanks for your patience.

**Comment by camacho** [comment]
See #126
