### ISSUE TITLE
Should we consider putting `homepage` before `bugs`?

### ISSUE THREAD

**Issue by revelt** [camacho/format-package#2]
I stumbled across [clinton](https://github.com/SamVerschueren/clinton) rule, [pkg-property-order](https://github.com/SamVerschueren/clinton/blob/master/docs/rules/pkg-property-order.md) (it's in default settings) which it alerts if `homepage` is listed before `bugs`.

Would it make sense to tweak the settings of `format-package` to pass that?

**Comment by camacho** [comment]
I'm curious if we should try to make this tool conform to another linter. IMO, this is all personal preference to some degree. I'd rather make it easier to customize it then keep adapting it to an unbounded set of possible tools. Maybe we could make a `format-package.config.js' file (or use cosmic-config) so it's easier for projects to use this tool in conjunction with other tools

**Comment by revelt** [comment]
It's logical. I'll close now, but if you still want to keep this, do re-open.
