### ISSUE TITLE
`prettier.format` requires `{parser: json}` option

### ISSUE THREAD

**Issue by vjpr** [camacho/format-package#22]
I couldn't get this working: https://github.com/camacho/format-package#formatter

~https://github.com/prettier/prettier/issues/322#issuecomment-283432929~

**Comment by vjpr** [comment]
So you have to pass in `{parser: 'json}` to `prettier.format`.

Should update the readme to indicate this.

**Comment by camacho** [comment]
would you be willing to put up a PR with update docs? i'll gladly review

**Comment by vjpr** [comment]
Done. https://github.com/camacho/format-package/pull/23
