### ISSUE TITLE
DoS vulnerability in yargs 11.1.0

### ISSUE THREAD

**Issue by vjrasane** [camacho/format-package#34]
Hello!

I'm using format-package as a non-development dependency in one of my projects. I've got Snyk configured to scan my dependencies for any security vulnerabilities and it reports that format-package has a denial of service vulnerability introduced through:

format-package@4.5.0 › yargs@11.1.0 › os-locale@2.1.0 › mem@1.1.0

Now I don't know how serious this can really be, and my project is a CLI so it doesn't really matter for me, but it'd be nice to get rid of the warnings.

The fix should be as easy as updating yargs to 12.0.2

**Comment by camacho** [comment]
This problem is now resolved
