### ISSUE TITLE
let's check, does it keep the new lines at the end of a file

### ISSUE THREAD

**Issue by revelt** [camacho/format-package#4]
hi!

I have a huge suspicion that the latest release removes the trailing new lines when saving over:

![newlines_bug](https://user-images.githubusercontent.com/8344688/30782586-e1b259e2-a12c-11e7-8667-2b4e8378cc86.gif)

Above, `format-package` removes trailing line break, Atom restores it upon a file save.

It's not good because it causes limbo of permanent changes in `git status`: my `precommit` hooks restore it, I commit it, then as part of `prepare` the `format-package` deletes the trailing line break which means new changes in Git... It's permanent unfinished commit limbo :)

That aside, rest works perfectly.

**Comment by camacho** [comment]
Sounds like a mistake on my end. Do you want to put up a PR that changes [formatter](lib/formatter.js) to attach a new line to the result of the `JSON.stringify` call?

**Comment by revelt** [comment]
I'm not familiar with the algorithm, if you do it it would be by magnitude faster. Is that all right?

**Comment by camacho** [comment]
I'll put up a PR for review. 

Also, checkout using `.gitattributes` file (like a `.gitignore`) as a mechanism to address this kind of issue across an entire project - it can address end of file issues and such

**Comment by camacho** [comment]
Should be resolved now that https://github.com/camacho/format-package/pull/5 has been merged and `3.0.2` has been published

**Comment by revelt** [comment]
I was thinking, how these kinds of bugs could have slipped through even though we have 100% coverage. Can it be because we're missing end-to-end tests? That is, having a "seed" of two files, one reference with desired fix, another with bad source, then using `execa` to run the cli upon the "bad" file, then read it as string and compare its results with the contents of "desired", reference file?

I know testing CLI apps is paid in the £&^$, not all of my CLI libs have end-to-end testing set. One of my approaches was to separate the API from the CLI into a separate library, I did that in [chlu](https://github.com/codsen/chlu). In that case API is string-to-string, and CLI functionality is just a shell, testing CLI becomes "either it works or not".

**Comment by camacho** [comment]
We could do a more functional testing approach. With Jest, I can mock the filesystem and use a snapshot to ensure the CLI produces the exact expected result with different configs

**Comment by revelt** [comment]
Yeah, that would be a proper way. At least one test which compares whole file contents of desired and actual files...

**Comment by camacho** [comment]
Published v4 which is fully asynchronous (means Node >=v7.6 for async/await) and with fixture testing (https://github.com/camacho/format-package/tree/master/__tests__)

**Comment by revelt** [comment]
Good stuff, looks impressive! I'm more of an AVA guy, my jest-fu is weak :)
