### ISSUE TITLE
Use Semantic Release

### ISSUE THREAD

**Issue by camacho** [camacho/format-package#49]
## Idea
Rather than having a manual release process, we should automate the workflow using  [`semantic-release`](https://github.com/semantic-release/semantic-release) .

>semantic-release automates the whole package release workflow including: determining the next version number, generating the release notes and publishing the package.
>
> This removes the immediate connection between human emotions and version numbers, strictly following the Semantic Versioning specification.

## Details
For this to work, there needs to be: 
- [ ] Settings change to [require signed commits](https://help.github.com/en/articles/about-commit-signature-verification)
- [ ] [Commit message linter](https://github.com/conventional-changelog/commitlint).
- [ ] Specified set of [lint rules](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional).
- [ ] Commit linting [`git` hook](https://github.com/conventional-changelog/commitlint#getting-started).
- [ ] [CI step](https://github.com/wilau2/circleci-commitlint-step) to ensure all commits in a PR are structured in such a way as to support an automated release process. Commitlint provides their own CI tool, but [only for Travis](https://commitlint.js.org/#/guides-ci-setup).
- [ ] Add `semantic-release` plugins for publishing
    - [ ] [`commit-analyzer`](https://github.com/semantic-release/commit-analyzer)
    - [ ] [`github`](https://github.com/semantic-release/github)
    - [ ] [`npm`](https://github.com/semantic-release/npm)
- [ ] [`NPM_TOKEN`](https://docs.npmjs.com/creating-and-viewing-authentication-tokens) created and set as environment variable for publishing the package to `npm`.
- [ ] [`GITHUB_TOKEN`](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line) created and set as an environment variable to publish a [GitHub release](https://help.github.com/en/articles/about-releases).

There are also a series of other `semantic-release` plugins that would also be nice to have for document generation.

cc / @peterkc

**Comment by peterkc** [comment]
I've started looking into this, WIP is in `feature/semantic-release` branch.

**Comment by camacho** [comment]
@peterkc how can I best help?

**Comment by peterkc** [comment]
@camacho I'll get back to this now, was researching a bit on the various options.

**Comment by camacho** [comment]
I started the work on moving to TypeScript. WIP is on `feature/semantic-release`

**Comment by camacho** [comment]
Stale - might revisit in the future

**Comment by camacho** [comment]
Stale - might revisit in the future
