### ISSUE TITLE
Fix README formatting inconsistencies 

### ISSUE THREAD

**Issue by camacho** [camacho/format-package#52]
When making commits, the formatting of the `README` file changes (see #50 as an example). I'm not sure what the root cause is, but it should be resolved to reduce noise.

**Comment by camacho** [comment]
I owe you a beer 🍺(or something of the sort) for all the work you've put in to making this project so **much** better!

**Comment by camacho** [comment]
Fixed in #54

**Comment by peterkc** [comment]
> I owe you a beer 🍺(or something of the sort) for all the work you've put in to making this project so **much** better!

Happy to contribute. `format-package` helps to facilitate a project that I had been wanting to do. A project to bootstrap development with minimal config and default workflows.

**Comment by camacho** [comment]
That's awesome. I've been working on something similar, although far more basic than what it seems you're building.
