### ISSUE TITLE
sort order within author key - name to go before email

### ISSUE THREAD

**Issue by revelt** [camacho/format-package#6]
Currently, by default, author key is sorted alphabetically and `author.email` appears before `author.name`. This even triggers `clinton` error, rule [`pkg-property-order`](https://github.com/SamVerschueren/clinton/blob/master/docs/rules/pkg-user-order.md).

Looking at it, it kindof makes sense to put author's name first, what do you think?

The question is, also, in theory, would the current algorithm be capable of controlling the order of deeper level keys.

**Comment by camacho** [comment]
yes, this is supported. checkout `transformations` as the mechanism for controlling sub property ordering and transforming

**Comment by camacho** [comment]
const sortScripts = require('sort-scripts');
// script sorting mechanism

const transformations = {
  author(key, prevValue) {
    // We don't care about the order of the rest
    const { name, email, ...rest } = prevValue;
    const nextValue = {
      name,
      email,
      ...rest
    }
    return [key, nextValue];
  },
  scripts(key, prevValue) {
    const nextValue = sortScripts(prevValue).reduce(
      (obj, [name, value]) => Object.assign({}, obj, { [name]: value }),
      {}
    );

    return [key, nextValue];
  },
};

module.exports = transformations;
