### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by camacho** [camacho/format-package#61]
In the past, I greatly disliked using any non-JS language to write JS. 

However, I've grown to really like the type safety and information that comes with TypeScript. It has sped up my development time, and it hasn't gotten in the way of writing vanilla JS, which means it can be gradually adopted.

Would this deter you @peterkc (or anyone else) from contributing?

**Comment by peterkc** [comment]
@camacho love TS, currently using it here at Blizzard. It was one of the things that I wanted to propose (along with a monorepo setup).

**Comment by camacho** [comment]
I think it would be good. What are you thinking about a monorepo?

**Comment by peterkc** [comment]
I was thinking of something like this, split the functionality with a focus on extensible. I'm currently using a similar structure for grouping related util modules.

```
dist/
docs/
scripts/
@format-packages/
    cli
    config
    core
    plugin-transform
    examples
```

`dist` would be the compiled `.ts` using `rollup` or `webpack`.

This should dove tail nicely with the `semanitc-release` enhancement. We should inspect the repos of `babel`, `eslint`, and `lerna`.

**Comment by camacho** [comment]
This sounds like a good idea. And I don't think it would be too difficult to setup. 

I just implemented a similar setup about a month ago using `learn`, Yarn `workspaces`, and TypeScript. I modeled it after some popular setups and found it to be very nice to use. 

I think `workspaces` + `lerna` + `commitlint` + `semantic-release` would make for a great flow. 

👍 I'm onboard with this idea.

**Comment by camacho** [comment]
It would be nice to bring [`sort-scripts`](https://github.com/camacho/sort-scripts) into the monorepo, as well.

**Comment by camacho** [comment]
PR #64 is up for TypeScript migration
