### ISSUE TITLE
sorting strings within arrays via CLI

### ISSUE THREAD

**Issue by revelt** [camacho/format-package#7]
hi
How would you set up the `format-package` CLI that it sorted all the strings within arrays as well?
I'm trying to offload some content into `package.json` in my next CLI tool and all I would like arrays sorted as well.
cheers

**Comment by camacho** [comment]
It is possible, but I feel like a bad decision. With arrays, order actually matters. Maps (objects in this case) explicitly do not care about order, so they are safe to sort. For an example, sorting `lint-staged` configs alphabetically would result in commands running out of order.

**Comment by revelt** [comment]
OK I'll then do the sorting separately, after `format-package` call, directly on related keys.

Thanks a lot for prompt response! Closing.
